// Exercise asynchronous execution controls without a compiler or browser.
import assert from 'node:assert/strict';
const elements = new Map();
globalThis.document = { getElementById(id) {
  if (!elements.has(id)) elements.set(id, { value: '', textContent: '', disabled: false,
    classList: { toggle() {} },
    listeners: {}, addEventListener(name, fn) { this.listeners[name] = fn; }, focus() {} });
  return elements.get(id);
} };
let allowConfirmation = true;
globalThis.confirm = () => allowConfirmation;
const get = id => elements.get(id);
let state, created, cancellation = 0, jobNumber = 0;
let stoppedBeforeCreated = false;
let submissionStatus = 202;
let compilers = ['gfortran'];
const optionCatalog = {
  gfortran: {presets: {default: [], debug: ['-O0', '-g'], optimized: ['-O3'], strict: ['-pedantic']}, extras: {warnings: ['-Wall'], fast_math: ['-ffast-math']}, note: 'GNU'},
  lfortran: {presets: {default: []}, extras: {fast_math: ['--fast']}, note: 'Experimental'},
};
const sleep = setTimeout;
globalThis.fetch = async (url, options = {}) => {
  let payload;
  if (url === './service.json') payload = { url: '' };
  else if (url === '/api/session') payload = { token: 'test-token', commit: '123abcdef', compiler: 'gfortran', compilers, timeout: 30, compiler_options: optionCatalog };
  else if (url === '../vendor/manifest.json') payload = { commit: '123abcdef' };
  else if (url === '/api/jobs') {
    created = JSON.parse(options.body); jobNumber++;
    assert.equal(options.headers['X-P2F-Token'], 'test-token');
    if (stoppedBeforeCreated) await new Promise(resolve => sleep(resolve, 10));
    payload = submissionStatus === 202 ? { id: String(jobNumber) } : { error: 'Provisioning failed' };
  } else if (url.endsWith('/cancel')) { cancellation++; payload = { cancelled: true }; }
  else payload = state;
  const status = url === '/api/jobs' ? submissionStatus : 200;
  return { ok: status < 400, status, json: async () => payload };
};
await import('../site/run/run.mjs');
assert.equal(get('run-both').disabled, false);
assert.match(get('connection').textContent, /123abcd/);
assert.equal(get('compiler').value, 'gfortran');
assert.equal(get('compiler-intel').disabled, true);
assert.equal(get('compiler-flang').disabled, true);
assert.equal(get('compiler-lfortran').disabled, true);

const result = { ok: true, mode: 'compare', seconds: 1.2, fortran: 'program input\nend program input\n', matches: true,
  build: { seconds: 0.8, stdout: 'Build: PASS', stderr: '' },
  python: { seconds: 0.2, stdout: '385\n', stderr: '' },
  execution: { seconds: 0.2, stdout: '385\n', stderr: '' } };
state = { state: 'done', result };
await get('compare').onclick();
assert.equal(created.mode, 'compare');
assert.equal(created.compiler, 'gfortran');
assert.deepEqual(created.compiler_options, {preset: 'default', warnings: false, fast_math: false});
get('compiler-preset').value = 'debug'; get('compiler-preset').onchange();
get('compiler-warnings').checked = true; get('compiler-warnings').onchange();
await get('compare').onclick();
assert.deepEqual(created.compiler_options, {preset: 'debug', warnings: true, fast_math: false});
assert.match(get('compiler-options-note').textContent, /-O0 -g -Wall/);
assert.match(get('status').textContent, /outputs match/);
assert.equal(get('python-output').textContent, '385\n');
assert.equal(get('fortran-output').textContent, '385\n');
assert.equal(get('python-time').textContent, '0.20 s');
assert.equal(get('download').disabled, false);
assert.equal(get('fortran-lines').textContent, '2 lines');

compilers = ['gfortran', 'ifx'];
await get('connect').onclick();
assert.equal(get('compiler-intel').disabled, false);
get('compiler').value = 'ifx';
get('compiler').onchange();
state = { state: 'done', result: { ...result, compiler: 'ifx' } };
await get('compare').onclick();
assert.equal(created.compiler, 'ifx');
assert.match(get('status').textContent, /ifx/);
compilers = ['gfortran', 'ifx', 'flang'];
await get('connect').onclick();
assert.equal(get('compiler-flang').disabled, false);
get('compiler').value = 'flang';
get('compiler').onchange();
state = { state: 'done', result: { ...result, compiler: 'flang' } };
await get('compare').onclick();
assert.equal(created.compiler, 'flang');
assert.match(get('status').textContent, /flang/);
compilers = ['gfortran', 'ifx', 'flang', 'lfortran'];
await get('connect').onclick();
assert.equal(get('compiler-lfortran').disabled, false);
get('compiler').value = 'lfortran';
get('compiler').onchange();
assert.equal(get('compiler-preset').value, 'default');
assert.equal(get('preset-debug').disabled, true);
assert.equal(get('compiler-warnings').disabled, true);
assert.equal(get('compiler-warnings').checked, false);
get('compiler-fast-math').checked = true; get('compiler-fast-math').onchange();
state = { state: 'done', result: { ...result, compiler: 'lfortran' } };
await get('compare').onclick();
assert.equal(created.compiler, 'lfortran');
assert.equal(created.compiler_options.fast_math, true);
assert.match(get('status').textContent, /lfortran/);
compilers = ['gfortran'];
await get('connect').onclick();
assert.equal(get('compiler').value, 'gfortran');
assert.equal(get('compiler-intel').disabled, true);
assert.equal(get('compiler-flang').disabled, true);
assert.equal(get('compiler-lfortran').disabled, true);

state = { state: 'running' };
const stale = get('run-both').onclick();
await new Promise(resolve => sleep(resolve, 10));
assert.equal(get('run-python').disabled, true);
assert.equal(get('stop').disabled, false);
assert.equal(get('compiler').disabled, true);
assert.equal(get('compiler-preset').disabled, true);
get('python').value = 'print(2)'; get('python').listeners.input();
assert.equal(get('download').disabled, true);
state = { state: 'done', result: { ...result, fortran: 'wrong stale output' } };
await stale;
assert.match(get('status').textContent, /discarded/);
assert.doesNotMatch(get('fortran').value, /wrong/);

state = { state: 'running' };
stoppedBeforeCreated = true;
const cancelled = get('run-python').onclick();
await get('stop').onclick();
state = { state: 'done', result };
await cancelled;
assert.equal(cancellation, 1);
assert.equal(get('status').textContent, 'Stopped');
assert.equal(get('stop').disabled, true);
assert.equal(get('run-python').disabled, false);
get('clear').onclick();
assert.equal(get('python-lines').textContent, '0 lines');
assert.equal(get('fortran-lines').textContent, '0 lines');
get('python').value = 'print(1)'; get('python').listeners.input();
stoppedBeforeCreated = false;
state = { state: 'done', result };
await get('translate').onclick();
const original = get('fortran').value;
get('live').checked = true;
get('edit-fortran').checked = true; get('edit-fortran').onchange();
assert.equal(get('fortran').readOnly, false);
assert.equal(get('live').checked, false);
assert.equal(get('live').disabled, true);
const edited = 'program edited\nprint *, 42\nend program edited\n';
get('fortran').value = edited; get('fortran').listeners.input();
assert.equal(get('fortran-title').textContent, 'Edited Fortran');
assert.equal(get('reset-fortran').disabled, false);
state = { state: 'done', result: { ...result, mode: 'compare-edit', fortran: edited } };
await get('compare').onclick();
assert.equal(created.mode, 'compare-edit');
assert.equal(created.fortran_source, edited);
get('clear').onclick();
assert.equal(get('python').value, '');
assert.equal(get('fortran').value, edited);
assert.equal(get('download').disabled, false);
state = { state: 'done', result: { ...result, mode: 'fortran-edit', fortran: edited } };
await get('run-fortran').onclick();
assert.equal(created.mode, 'fortran-edit');
assert.equal(created.source, '');
assert.equal(created.fortran_source, edited);
get('python').value = 'print(42)'; get('python').listeners.input();
allowConfirmation = false;
const priorJobs = jobNumber;
await get('translate').onclick();
assert.equal(jobNumber, priorJobs);
get('reset-fortran').onclick();
assert.equal(get('fortran').value, edited);
allowConfirmation = true;
get('reset-fortran').onclick();
assert.equal(get('fortran').value, original);
get('fortran').value = edited; get('fortran').listeners.input();
state = { state: 'running' };
const editStale = get('run-fortran').onclick();
await new Promise(resolve => sleep(resolve, 10));
get('fortran').value = edited + '! newer\n'; get('fortran').listeners.input();
state = { state: 'done', result: { ...result, mode: 'fortran-edit', fortran: edited } };
await editStale;
assert.match(get('status').textContent, /discarded/);
assert.match(get('fortran').value, /newer/);
get('edit-fortran').checked = false; get('edit-fortran').onchange();
assert.equal(get('fortran').readOnly, true);
assert.match(get('fortran').value, /newer/);
submissionStatus = 503;
await get('translate').onclick();
assert.match(get('diagnostics').textContent, /Provisioning failed/);
assert.equal(get('translate').disabled, false);
assert.equal(get('run-both').disabled, false);
submissionStatus = 429;
await get('run-python').onclick();
assert.equal(get('run-python').disabled, false);
submissionStatus = 403;
await get('translate').onclick();
assert.equal(get('translate').disabled, true);
console.log('Execution UI: outputs, timings, stale results, early Stop, and Clear passed');
