import assert from 'node:assert/strict';
import {sourceTools, translationSettings} from '../site/source_tools.mjs';
const elements = new Map();
const get = id => { if (!elements.has(id)) elements.set(id, {value: '', checked: true, click() {this.clicked = true;}}); return elements.get(id); };
let allowed = true, pauses = 0, pythonChanges = 0, fortranChanges = 0, requested = 0, undoable = false;
globalThis.confirm = () => allowed;
const editor = value => ({value, getValue() {return this.value;}, setValue(v, undo) {this.value = v; undoable = undo;}, focus() {}});
const input = editor('print(1)\n'), output = editor('program old\nend program old\n');
let answer = {ok: true, count: 1, annotated: 'def f(x: int): return x\nf(2)\n', diagnostics: 'Review suggestions'};
const tools = sourceTools({get, input, output, pause: () => pauses++, pythonChanged: () => pythonChanges++,
  fortranChanged: source => {fortranChanges++; output.setValue(source);},
  requestAnnotations: async () => {requested++; return answer;}});
const file = (name, source) => {const bytes = new TextEncoder().encode(source); return {name, size: bytes.length, arrayBuffer: async () => bytes.buffer};};
async function load(language, value) {get(`file-${language}`).files = [value]; await get(`file-${language}`).onchange();}
get('load-python-file').onclick(); assert.equal(get('file-python').clicked, true);
allowed = false; await load('python', file('test.py', 'print(2)\n'));
assert.equal(input.value, 'print(1)\n'); assert.equal(pauses, 0);
allowed = true; await load('python', file('test.py', '\ufeffprint(2)\r\n'));
assert.equal(input.value, 'print(2)\r\n'); assert.equal(undoable, true);
assert.equal(output.value, 'program old\nend program old\n');
assert.equal(tools.fortranFilename(), 'test_p.f90');
assert.equal(requested, 0); assert.equal(pauses, 1);
await load('python', {name: 'big.py', size: 100001});
assert.match(get('source-tools-status').textContent, /100 KB/);
await load('python', {name: 'utf16.py', size: 2, arrayBuffer: async () => new Uint8Array([255, 254]).buffer});
assert.match(get('source-tools-status').textContent, /Could not load/);
await load('python', file('binary.py', '\0'));
assert.match(get('source-tools-status').textContent, /binary/);
assert.equal(input.value, 'print(2)\r\n');
await load('fortran', file('custom.f90', 'program custom\nend program custom\n'));
assert.match(output.value, /program custom/); assert.equal(fortranChanges, 1);
assert.equal(tools.fortranFilename(), 'custom.f90'); assert.equal(input.value, 'print(2)\r\n');
input.value = 'def f(x): return x\nf(2)\n';
await get('suggest-annotations').onclick();
assert.equal(get('annotation-preview-panel').hidden, false);
assert.equal(get('annotation-preview').value, answer.annotated);
assert.equal(get('annotation-apply').disabled, false);
assert.equal(input.value, 'def f(x): return x\nf(2)\n');
input.value += '# newer\n'; get('annotation-apply').onclick();
assert.match(get('source-tools-status').textContent, /changed after/);
await get('suggest-annotations').onclick();
allowed = false; get('annotation-apply').onclick();
assert.match(input.value, /newer/);
allowed = true; get('annotation-apply').onclick();
assert.equal(input.value, answer.annotated);
assert.equal(undoable, true); assert.equal(pythonChanges, 2);
assert.match(output.value, /program custom/);
get('translation-int-kind').value = 'int64'; get('translation-comments').checked = false;
assert.deepEqual(translationSettings(get), {int_kind: 'int64', preserve_comments: false});
answer = {ok: false, diagnostics: 'invalid syntax'};
await get('suggest-annotations').onclick();
assert.match(get('source-tools-status').textContent, /invalid syntax/);
assert.equal(get('annotation-apply').disabled, true);
console.log('PASS local UTF-8 file loading, limits, confirmations, paused live actions, annotation preview and stale Apply');
